apiVersion: v1
name: vcwaltid
version: 0.0.12
appVersion: 0.0.1
home: https://github.com/hesusruiz/vcwaltid
description: A Helm chart for running the i4Trust DSBA vcwaltid.
keywords:
- i4Trust
- experimentation framework
- proof of concept
- verifiable credentials
maintainers:
- name: wistefan
  email: stefan.wiedemann@fiware.org